---
- name: Check if ELREPO repo is already configured.
  stat: path={{ elrepo_repofile_path }}
  register: elrepo_repofile_result

- name: Install ELREPO repo.
  yum:
    name: "{{ elrepo_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not elrepo_repofile_result.stat.exists

- name: Import ELREPO GPG key.
  rpm_key:
    key: "{{ elrepo_repo_gpg_key_url }}"
    state: present
  when: not elrepo_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install kernel-lt packages
  yum:
      name: '{{ item.name }}'
      state: '{{ item.state }}'
      enablerepo: '{{ elrepo_kernel_repo }}'
  with_items: '{{ elrepo_kernel_packages }}'

- name: "Setting default kernel"
  lineinfile:
    path: "/etc/default/grub"
    regexp: '^GRUB_DEFAULT='
    line: "GRUB_DEFAULT=0"
  register: grub_changed
  notify: 
    - Recreate grub config

- debug: var=grub_changed["changed"]
