---
- name: Install Heketi server package
  yum: 'name="{{ heketi_daemon_package }}"  state=present'

- name: Create a new ssh key
  shell: ssh-keygen -f "{{ heketi_ssh_private_key_file }}" -t rsa -N ''
  args:
    creates: "{{ heketi_ssh_private_key_file }}"

- name: Update key permissions
  file:
    path: "{{ item }}"
    owner: "{{ heketi_user }}"
    group: "{{ heketi_user }}"
  with_items:
    - "{{ heketi_ssh_private_key_file }}"
    - "{{ heketi_ssh_public_key_file }}"

- name: Update Heketi config file
  template:
    src: heketi.json.j2
    dest: '{{ heketi_config_file }}'
    owner: "root"
    group: "{{ heketi_user }}"
