---
- name: Partition NFS storage
  parted:
    device: '{{ nfs_disk }}'
    number: '{{ nfs_disk_partition }}'
    align: '{{ nfs_disk_align }}'
    part_start: '{{ nfs_disk_start }}'
    part_end: '{{ nfs_disk_end }}'
    part_type: '{{ nfs_disk_part_type }}'
    state: present

- name: Create an XFS filesystem on the storage
  filesystem:
    fstype: xfs
    dev: '{{ nfs_disk }}{{ nfs_disk_partition}}'

- name: Mount the storage
  mount:
    src: '{{ nfs_disk }}{{ nfs_disk_partition }}'
    path: '{{ nfs_disk_mount_point }}'
    fstype: 'xfs'
    state: 'mounted'
