---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Get public key from heketi_server
  command: cat '/etc/heketi/heketi_key.pub'
  delegate_to: "{{ groups['heketi-server'][0] }}"
  register: heketi_ssh_public_key 
  changed_when: false

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Install ssh key
  authorized_key:
    user: "{{ heketi_ssh_user }}"
    state: present
    key: "{{ heketi_ssh_public_key.stdout }}"

- name: Update User environment
  become: true
  become_user: '{{ heketi_user }}'
  lineinfile:
    path: "~/.bash_profile"
    regexp: '^export HEKETI_CLI_SERVER'
    line: 'export HEKETI_CLI_SERVER=http://{{ heketi_server }}:{{ heketi_server_port }}'
    state: present
    create: yes
